import{chromium}from'playwright';
import{readFile}from'node:fs/promises';
import assert from'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const base=process.env.VPM_TEST_URL||'http://127.0.0.1:8087';
let brand={name:'VPS Manager',logo:null};
await page.route('**/api/v1/branding',r=>r.fulfill({json:brand}));
await page.route('**/api/v1/auth/me',async r=>{const res=await r.fetch();const body=await res.json();await r.fulfill({response:res,json:{...body,branding:brand}});});
await page.route('**/api/v1/settings',async r=>{if(r.request().method()==='POST'&&r.request().postDataJSON().name==='branding'){brand=r.request().postDataJSON().value;await r.fulfill({json:{message:'OK'}});}else await r.continue();});
await page.goto(base);await page.locator('.login-card').waitFor();
const box=await page.locator('.login-card').boundingBox();assert(box.width<=480&&box.height<620);
await page.screenshot({path:'test-results/login-compact.png'});
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'test-results/login-compact-mobile.png'});
await page.setViewportSize({width:1440,height:900});
const password=(await readFile('storage/LOCAL-ACCESS.txt','utf8')).match(/Senha: (.+)/)[1].trim();
await page.getByLabel('E-mail',{exact:true}).fill('admin@vpsmanager.local');await page.getByLabel('Senha',{exact:true}).fill(password);
await page.getByRole('button',{name:'Entrar no painel'}).click();await page.locator('[data-route=settings]').click();
await page.locator('#branding-form').waitFor();
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6xO8AAAAASUVORK5CYII=','base64');
await page.locator('#branding-form input[name=logo]').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:png});
await page.locator('.branding-preview .custom-logo').waitFor();await page.locator('#branding-form button[type=submit]').click();
await page.locator('.brand .custom-logo').waitFor();assert(brand.logo.startsWith('data:image/png;base64,'));
await page.screenshot({path:'test-results/branding-settings.png',fullPage:true});
await page.locator('#branding-form input[name=reset]').check();await page.locator('#branding-form button[type=submit]').click();
await page.locator('.brand img:not(.custom-logo)').waitFor();assert.equal(brand.logo,null);
// Assert popup uses only a one-time POST ticket, not credentials or a query token.
await page.route('**/api/v1/databases',r=>r.fulfill({json:{data:[{id:42,name:'u1_test',status:'active',config:{username:'u1_test'},created_at:1700000000,owner_id:1,server_id:1}]}}));
await page.route('**/api/v1/databases/42/access',r=>r.fulfill({json:{name:'u1_test',username:'u1_test',host:'localhost',port:3306,status:'active',created_at:1700000000,phpmyadmin_url:base+'/phpmyadmin/'}}));
await page.route('**/api/v1/databases/42/phpmyadmin',r=>r.fulfill({json:{ticket:'a'.repeat(64),action:'/api/v1/phpmyadmin/open'}}));
let posted=false;
await page.context().route('**/api/v1/phpmyadmin/open',async r=>{assert.equal(r.request().method(),'POST');assert.equal(r.request().postData(),'ticket='+'a'.repeat(64));assert(!r.request().url().includes('ticket='));posted=true;await r.fulfill({contentType:'text/html',body:'<h1>phpMyAdmin</h1>'});});
await page.locator('[data-route=databases]').click();await page.locator('[data-database="42"]').click();
const popupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'Abrir phpMyAdmin',exact:true}).click();const popup=await popupPromise;
await popup.getByRole('heading',{name:'phpMyAdmin'}).waitFor();assert(posted);assert.equal(await popup.evaluate(()=>window.opener),null);
assert.deepEqual(errors,[]);await browser.close();console.log('PASS compact desktop/mobile login, admin branding upload/reset, private phpMyAdmin POST popup');
