location = /api/v1/files/upload-chunk {
    client_max_body_size 8m;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /opt/vpsmanager/current/public/index.php;
    fastcgi_pass unix:/run/php/vpsmanager.sock;
    fastcgi_read_timeout 190s;
}
