// Regenerate external CSS from the pinned, unmodified Ace distribution for strict CSP.
import {readFile,writeFile} from 'node:fs/promises';
const base=new URL('../public/vendor/ace/',import.meta.url);
const css=[];
for(const file of ['ace.js','theme-chrome.js','ext-searchbox.js']){
 const source=await readFile(new URL(file,base),'utf8');
 for(const match of source.matchAll(/(?:module\.exports\s*=\s*|dom\.importCssString\()("(?:\\.|[^"\\])*")/g)){
  const value=JSON.parse(match[1]);
  if(value.includes('{')&&value.includes('.ace'))css.push(value);
 }
}
if(css.length<5)throw new Error('Ace CSS extraction incomplete');
await writeFile(new URL('editor.css',base),'/* Ace CSS, generated by scripts/vendor-editor.mjs; see LICENSE. */\n'+css.join('\n'));
console.log(`Extracted ${css.length} Ace stylesheets for strict CSP.`);
